In [34]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import json

movies = pd.read_csv('/workspaces/cesarseneca-K-nearest/data/raw/tmdb_5000_movies.csv')
credits = pd.read_csv('/workspaces/cesarseneca-K-nearest/data/raw/tmdb_5000_credits.csv')

In [35]:
print("Primeras 10 filas de Movies: \n" , movies.head())
print("Forma del dataset" ,movies.shape)
print("Primeras 10 filas de Credits: \n" , credits.head())
print("Forma del dataset", credits.shape)

Primeras 10 filas de Movies:
       budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bondâ€™s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...
3  [{"name": "Legendary Pictures", "id": 923}, {"...
4        [{"name": "Walt Disney Pictures", "id": 2}]

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title  vote_average  vote_count
0                                    Avatar           7.2       11800
1  Pirates of the Caribbean: At World's End           6.9        4500
2                                   Spectre           6.3        4466
3                     The Dark Knight Rises           7.6        9106
4                               John Carter           6.1        2124
Forma del dataset (4803, 20)
Primeras 10 filas de Credits:
    movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
Forma del dataset (4803, 4)

In [36]:
import sqlite3
conn = sqlite3.connect('moviesDB.sqlite')
conn.execute("DROP TABLE IF EXISTS movies_table")
conn.execute("DROP TABLE IF EXISTS credits_table")

movies.to_sql('movies_table', conn, index=False)
credits.to_sql('credits_table', conn, index=False)

query = '''
    SELECT *
    FROM movies_table
    INNER JOIN credits_table
    USING (title);
'''

moviesDB = pd.read_sql_query(query, conn)
conn.close()

In [37]:
print("Primeras 10 filas de Movies: \n" , moviesDB.head())
print("Forma del dataset" ,moviesDB.shape)

Primeras 10 filas de Movies:
       budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4  [{"id": 818, "name": "based on novel"}, {"id":...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577
1  Captain Barbossa, long believed to be dead, ha...  139.082615
2  A cryptic message from Bondâ€™s past sends him o...  107.376788
3  Following the death of District Attorney Harve...  112.312950
4  John Carter is a war-weary, former military ca...   43.926995

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995
1  Pirates of the Caribbean: At World's End          6.9       4500      285
2                                   Spectre          6.3       4466   206647
3                     The Dark Knight Rises          7.6       9106    49026
4                               John Carter          6.1       2124    49529

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...
1  [{"cast_id": 4, "character": "Captain Jack Spa...
2  [{"cast_id": 1, "character": "James Bond", "cr...
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4  [{"cast_id": 5, "character": "John Carter", "c...

                                                crew
0  [{"credit_id": "52fe48009251416c750aca23", "de...
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]
Forma del dataset (4809, 23)

In [38]:
moviesDB = moviesDB[["movie_id","title","overview","genres","keywords","cast","crew"]]
moviesDB

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [39]:
moviesDB.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [40]:
moviesDB.dropna(inplace = True)

In [41]:
moviesDB["genres"] = moviesDB["genres"].apply(lambda x: [item["name"] for item in json.loads(x)] if pd.notna(x) else None)
moviesDB["keywords"] = moviesDB["keywords"].apply(lambda x: [item["name"] for item in json.loads(x)] if pd.notna(x) else None)
moviesDB["cast"] = moviesDB["cast"].apply(lambda x: [item["name"] for item in json.loads(x)][:3] if pd.notna(x) else None)
moviesDB["crew"] = moviesDB["crew"].apply(lambda x: next((item["name"] for item in json.loads(x) if item["job"] == "Director"), None) if pd.notna(x) else None)
moviesDB["overview"] = moviesDB["overview"].apply(lambda x: [x] if pd.notna(x) else None)
moviesDB

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In the 22nd century, a paraplegic Marine is d...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,206647,Spectre,[A cryptic message from Bondâ€™s past sends him ...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",Sam Mendes
3,49026,The Dark Knight Rises,[Following the death of District Attorney Harv...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,49529,John Carter,"[John Carter is a war-weary, former military c...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,[El Mariachi just wants to play his guitar and...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",Robert Rodriguez
4805,72766,Newlyweds,[A newlywed couple's honeymoon is upended by t...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",Edward Burns
4806,231617,"Signed, Sealed, Delivered","[""Signed, Sealed, Delivered"" introduces a dedi...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",Scott Smith
4807,126186,Shanghai Calling,[When ambitious New York attorney Sam is sent ...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",Daniel Hsia
4808,25975,My Date with Drew,[Ever since the second grade when he first saw...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",Brian Herzlinger

In [42]:
def remove_spaces_from_list(lst):
    return [item.replace(" ", "") for item in lst] if isinstance(lst, list) else lst

moviesDB[["genres", "cast", "keywords"]] = moviesDB[["genres", "cast", "keywords"]].applymap(remove_spaces_from_list)
moviesDB["crew"] = moviesDB["crew"].str.replace(" ", "")

print(moviesDB.head())

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                            overview  \
0  [In the 22nd century, a paraplegic Marine is d...
1  [Captain Barbossa, long believed to be dead, h...
2  [A cryptic message from Bondâ€™s past sends him ...
3  [Following the death of District Attorney Harv...
4  [John Carter is a war-weary, former military c...

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]
1                  [Adventure, Fantasy, Action]
2                    [Action, Adventure, Crime]
3              [Action, Crime, Drama, Thriller]
4           [Action, Adventure, ScienceFiction]

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...
1  [ocean, drugabuse, exoticisland, eastindiatrad...
2  [spy, basedonnovel, secretagent, sequel, mi6, ...
3  [dccomics, crimefighter, terrorist, secretiden...
4  [basedonnovel, mars, medallion, spacetravel, p...

                                            cast              crew
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]      JamesCameron
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]     GoreVerbinski
2      [DanielCraig, ChristophWaltz, LÃ©aSeydoux]         SamMendes
3      [ChristianBale, MichaelCaine, GaryOldman]  ChristopherNolan
4    [TaylorKitsch, LynnCollins, SamanthaMorton]     AndrewStanton

In [43]:
def list_to_string(lst):
    return ",".join(lst) if isinstance(lst, list) else ""

moviesDB["genres"] = moviesDB["genres"].apply(list_to_string)
moviesDB["keywords"] = moviesDB["keywords"].apply(list_to_string)
moviesDB["cast"] = moviesDB["cast"].apply(list_to_string)
moviesDB["overview"] = moviesDB["overview"].apply(list_to_string)
moviesDB["overview"] = moviesDB["overview"].str.replace(",", "")

In [44]:
moviesDB["tags"] = moviesDB["overview"] + " " + moviesDB["genres"] + " " + moviesDB["keywords"]  + " " + moviesDB["cast"] + " " + moviesDB["crew"]
moviesDB["tags"] = moviesDB["tags"].str.replace(",", " ")

In [45]:
moviesDB.iloc[0].tags

'In the 22nd century a paraplegic Marine is dispatched to the moon Pandora on a unique mission but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

moviesDB["tags"] = moviesDB["tags"].fillna("")
cv = CountVectorizer(max_features=5000 ,stop_words='english')
vectors = cv.fit_transform(moviesDB['tags']).toarray()

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [48]:
moviesDB

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,In the 22nd century a paraplegic Marine is dis...,"Action,Adventure,Fantasy,ScienceFiction","cultureclash,future,spacewar,spacecolony,socie...","SamWorthington,ZoeSaldana,SigourneyWeaver",JamesCameron,In the 22nd century a paraplegic Marine is dis...
1,285,Pirates of the Caribbean: At World's End,Captain Barbossa long believed to be dead has ...,"Adventure,Fantasy,Action","ocean,drugabuse,exoticisland,eastindiatradingc...","JohnnyDepp,OrlandoBloom,KeiraKnightley",GoreVerbinski,Captain Barbossa long believed to be dead has ...
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"Action,Adventure,Crime","spy,basedonnovel,secretagent,sequel,mi6,britis...","DanielCraig,ChristophWaltz,LÃ©aSeydoux",SamMendes,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"Action,Crime,Drama,Thriller","dccomics,crimefighter,terrorist,secretidentity...","ChristianBale,MichaelCaine,GaryOldman",ChristopherNolan,Following the death of District Attorney Harve...
4,49529,John Carter,John Carter is a war-weary former military cap...,"Action,Adventure,ScienceFiction","basedonnovel,mars,medallion,spacetravel,prince...","TaylorKitsch,LynnCollins,SamanthaMorton",AndrewStanton,John Carter is a war-weary former military cap...
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"Action,Crime,Thriller","unitedstatesâ€“mexicobarrier,legs,arms,paperknif...","CarlosGallardo,JaimedeHoyos,PeterMarquardt",RobertRodriguez,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"Comedy,Romance",,"EdwardBurns,KerryBishÃ©,MarshaDietlein",EdwardBurns,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed Sealed Delivered"" introduces a dedicat...","Comedy,Drama,Romance,TVMovie","date,loveatfirstsight,narration,investigation,...","EricMabius,KristinBooth,CrystalLowe",ScottSmith,"""Signed Sealed Delivered"" introduces a dedicat..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,"DanielHenney,ElizaCoupe,BillPaxton",DanielHsia,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,"obsession,camcorder,crush,dreamgirl","DrewBarrymore,BrianHerzlinger,CoreyFeldman",BrianHerzlinger,Ever since the second grade when he first saw ...

In [50]:
def recommend(movie):
    user_words = movie.lower().split()
    mask = moviesDB["title"].str.lower().str.contains('|'.join(user_words))
    matched_movies = moviesDB[mask]

    if matched_movies.empty:
        print("Â¡PelÃ­cula no encontrada!")
        return

    movie_index = matched_movies.index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    print(f"Recomendaciones para pelÃ­culas con las palabras '{movie}':")
    for i, dist in movie_list:
        recommended_movie = moviesDB.iloc[i].title
        print(f"{recommended_movie} (Similitud: {dist:.2f})")

elegir = input("Ingrese el nombre de la pelÃ­cula: ")
recommend(elegir)

Recomendaciones para pelÃ­culas con las palabras 'games':
The Hunger Games: Catching Fire (Similitud: 0.37)
The Hunger Games (Similitud: 0.36)
The Hunger Games: Mockingjay - Part 1 (Similitud: 0.31)
Journey 2: The Mysterious Island (Similitud: 0.20)
Mad Max Beyond Thunderdome (Similitud: 0.19)